spring:
  profiles:
    active:
    - dev
---
server:
  port: 8080

eureka:
  instance:
    instance-id: msc-dept-8080
    prefer-ip-address: true
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

spring:
  profiles: dev
  application:
    name: msc-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

mybatis:
  type-aliases-package: cn.xmut.msc.domain
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
  - classpath:mybatis/mapper/*.xml

info:
  app.name: msc-eureka
  company.anme: www.xmut.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$
